# SPDX-License-Identifier: Apache-2.0
"""Compatibility exports for the family-local Wan pipeline configuration."""

from fastvideo.models.wan.pipeline_config import (
    BaseEncoderOutput,
    CLIPVisionConfig,
    DiTConfig,
    EncoderConfig,
    FastWan2_1_T2V_480P_Config,
    FastWan2_2_TI2V_5B_Config,
    LucyEditDevConfig,
    PipelineConfig,
    SelfForcingWan2_2_T2V480PConfig,
    SelfForcingWanT2V480PConfig,
    T5Config,
    VAEConfig,
    WAN2_1ControlCLIPVisionConfig,
    WANV2VConfig,
    Wan2_2_I2V_A14B_Config,
    Wan2_2_T2V_A14B_Config,
    Wan2_2_TI2V_5B_Config,
    WanI2V480PConfig,
    WanI2V720PConfig,
    WanT2V480PConfig,
    WanT2V720PConfig,
    WanVAEArchConfig,
    WanVAEConfig,
    WanVideoArchConfig,
    WanVideoConfig,
    t5_postprocess_text,
)

__all__ = [
    "BaseEncoderOutput",
    "CLIPVisionConfig",
    "DiTConfig",
    "EncoderConfig",
    "FastWan2_1_T2V_480P_Config",
    "FastWan2_2_TI2V_5B_Config",
    "LucyEditDevConfig",
    "PipelineConfig",
    "SelfForcingWan2_2_T2V480PConfig",
    "SelfForcingWanT2V480PConfig",
    "T5Config",
    "VAEConfig",
    "WAN2_1ControlCLIPVisionConfig",
    "WANV2VConfig",
    "Wan2_2_I2V_A14B_Config",
    "Wan2_2_T2V_A14B_Config",
    "Wan2_2_TI2V_5B_Config",
    "WanI2V480PConfig",
    "WanI2V720PConfig",
    "WanT2V480PConfig",
    "WanT2V720PConfig",
    "WanVAEArchConfig",
    "WanVAEConfig",
    "WanVideoArchConfig",
    "WanVideoConfig",
    "t5_postprocess_text",
]
