# SPDX-License-Identifier: Apache-2.0
"""Compatibility imports for the family-local Wan VAE.

Keep aliases, including the cache context variables, identical to the canonical
objects. New Wan code belongs in ``fastvideo.models.wan.vae``.
"""

from fastvideo.models.wan.vae import (
    CACHE_T,
    AutoencoderKLWan,
    AvgDown3D,
    DiagonalGaussianDistribution,
    DupUp3D,
    EntryClass,
    ParallelTiledVAE,
    WanAttentionBlock,
    WanCausalConv3d,
    WanDecoder3d,
    WanEncoder3d,
    WanMidBlock,
    WanRMS_norm,
    WanResample,
    WanResidualBlock,
    WanResidualDownBlock,
    WanResidualUpBlock,
    WanUpBlock,
    WanUpsample,
    WanVAEConfig,
    _is_wan_vae_codec,
    feat_cache,
    feat_idx,
    first_chunk,
    forward_context,
    is_first_frame,
    patchify,
    unpatchify,
    use_light_vae,
)

__all__ = [
    "CACHE_T",
    "AutoencoderKLWan",
    "AvgDown3D",
    "DiagonalGaussianDistribution",
    "DupUp3D",
    "EntryClass",
    "ParallelTiledVAE",
    "WanAttentionBlock",
    "WanCausalConv3d",
    "WanDecoder3d",
    "WanEncoder3d",
    "WanMidBlock",
    "WanRMS_norm",
    "WanResample",
    "WanResidualBlock",
    "WanResidualDownBlock",
    "WanResidualUpBlock",
    "WanUpBlock",
    "WanUpsample",
    "WanVAEConfig",
    "_is_wan_vae_codec",
    "feat_cache",
    "feat_idx",
    "first_chunk",
    "forward_context",
    "is_first_frame",
    "patchify",
    "unpatchify",
    "use_light_vae",
]
